# Generated by Django 4.2.4 on 2023-08-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("1", "Macbook"),
                            ("2", "Asus-Laptop"),
                            ("3", "Monitor"),
                            ("4", "Laptop-Stand"),
                            ("5", "HDMI"),
                            ("6", "Keyboard"),
                            ("7", "Mouse"),
                        ],
                        max_length=50,
                    ),
                ),
                ("asset_id", models.CharField(max_length=50, unique=True)),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                ("manufact_user", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=150)),
                ("purchase_date", models.DateField()),
                ("condition", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="AssignManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_returned", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.asset"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
