# Generated by Django 4.2.4 on 2023-08-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmanager",
            name="request_to_accept",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignmanager",
            name="request_to_return",
            field=models.BooleanField(default=False),
        ),
    ]
